routes/web.php
<?php

Route::get('/',function(){
    return redirect()->route('login');
});

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });

    Route::group(['middleware' => 'auth','prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);

        Route::group(['middleware' => ['permission:view-product|modify-product']],function(){
            Route::resource('product','ProductController');
        });

        Route::group(['middleware' => ['permission:view-category|modify-category']],function(){
            Route::resource('product-category','ProductCategoryController');
        });

        Route::group(['middleware' => ['permission:view-setting|setting-modification']], function () {
            Route::resource('settings','SettingController');
        });
        Route::group(['middleware' => ['permission:view-language|language-modification']], function () {
            Route::resource('languages','LanguageController');
        });
        Route::group(['middleware' => ['permission:view-user|user-modification|add-new-user']], function () {
            Route::resource('/users','UserController');
        });
        Route::group(['middleware' => ['permission:view-role|role-modification|add-new-role']], function () {
            Route::resource('/roles','UserRoleController');
        });
        Route::resource('/users/profile','EditProfileController',['as' => 'users']);

        //ajax upload image
        Route::post('/save-temp-image', ['as' => 'dropzoneSaveTempImage', 'uses' => 'ImageController@dropzoneSaveTempImage']);
        Route::post('/save-multi-temp-image', ['as' => 'dropzoneSaveMultiTempImage', 'uses' => 'ImageController@dropzoneSaveMultiTempImage']);
        Route::post('/save-summernote-image',['as' => 'summernoteSaveImage', 'uses' => 'ImageController@summernoteSaveImage']);
        Route::get('/get-image-list-by-object',['as' => 'getImageList', 'uses' => 'ImageController@getImageList']);
        Route::post('/delete-image-by-object',['as' => 'deleteDropzoneImage', 'uses' => 'ImageController@deleteDropzoneImage']);
        Route::post('/set-order-category',['as' => 'setOrderCategory', 'uses' => 'ProductCategoryController@setOrder']);
    });
});

resources/views/admin/category/add-update.blade.php
@extends('admin.layouts.master')

@section('page-css')
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/vendors.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/forms/icheck/icheck.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/forms/icheck/custom.css">
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ isset($category) ? 'Update' : 'Add' }} Product Category</h4>
            </div>

            @if(isset($category))
            {{ Form::model($category,['route' => ['admin.product-category.update',$category->id], 'method' => 'PUT']) }}
            @else
            {{ Form::open(['route' => 'admin.product-category.store', 'method' => 'POST']) }}
            @endif
            @csrf
            <div class="card-content">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <fieldset class="form-group">
                                <label>Product Category Image (Aspec Ratio 1:1) <span class="text-danger">*</span></label>
                                @component('admin.common.single_dropzone',['id' => "categoryDropzone",'object' => isset($category) ? $category : null, 'width' => 150, 'height' => 150,'collection_key' => 'image'])@endcomponent
                            </fieldset>
                        </div>
                        <div class="col-md-6">
                            <ul class="nav nav-tabs nav-top-border no-hover-bg" role="tablist">
                                @foreach(['en','kh','zh'] as $key => $lang)
                                <li class="nav-item">
                                    <a class="nav-link {{ $key ==0 ? 'active' : '' }}" id="base-{{$lang}}" data-toggle="tab" aria-controls="{{$lang}}" href="#{{$lang}}" role="tab" aria-selected="true">
                                        <img width="30px" src="{{asset('client/images/'.$lang.'.jpeg')}}" alt="">
                                    </a>
                                </li>
                                @endforeach
                            </ul>
                            <div class="tab-content px-1 pt-1">
                                @foreach(['en','kh','zh'] as $key => $lang)
                                    <div class="tab-pane {{ $key == 0 ? 'active' : ''}}" id="{{$lang}}" role="tabpanel" aria-labelledby="base-{{$lang}}">
                                        <fieldset class="form-group">
                                            <label for="basicInput">Name <img width="20px" src="{{asset('client/images/'.$lang.'.jpeg')}}" alt=""></label>
                                            {!! Form::text('name['.$lang.']',isset($category) ? $category->getTranslation('name',$lang) : null,['class' => 'form-control', 'placeholder' => 'Enter category name']) !!}
                                            @component('admin.common.error_helper_text',['key' => "name.$lang"])@endcomponent
                                        </fieldset>
                                        <fieldset class="form-group">
                                            <label for="basicInput">Description <img width="20px" src="{{asset('client/images/'.$lang.'.jpeg')}}" alt=""></label>
                                            {!! Form::textarea('description['.$lang.']',isset($category) ? $category->getTranslation('description',$lang) : null,['class' => 'form-control', 'placeholder' => 'Enter category description','rows' => '4']) !!}
                                            @component('admin.common.error_helper_text',['key' => "description"])@endcomponent
                                        </fieldset>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
                @if(isset($category))
                    @can('modify-category')
                    <div class="card-footer">
                        <a href="{{route('admin.product-category.index')}}" class="btn grey btn-outline-secondary">Discard</a>
                        <button type="submit" class="btn btn-outline-primary">Save changes</button>
                    </div>
                    @endcan
                @else
                    @can('add-new-category')
                    <div class="card-footer">
                        <a href="{{route('admin.product-category.store')}}" class="btn grey btn-outline-secondary">Discard</a>
                        <button type="submit" class="btn btn-outline-primary">Save changes</button>
                    </div>
                    @endcan
                @endif
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layouts.master')
@section('content')
@include(
    'admin.common.success_alert',['key' => 'success']
)
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Product Categories</h4>
                <div class="heading-elements">
                    @can('add-new-category')
                    <a href="{{ route('admin.product-category.create') }}" class="btn btn-sm btn-icon btn-success">
                        <i class="ft-plus white"></i> Add New
                    </a>
                    @endcan
                </div>
            </div>
            <div class="card-content">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="bg-primary">
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Image</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody id="sortable">
                                @forelse($categories as $key => $category)
                                    <tr data-id={{ $category->id }}>
                                        <td> <span class="handle">::</span></td>
                                        <td>{{ $category->getTranslation('name','en') }}</td>
                                        <td>{{ $category->getTranslation('description','en') }}</td>
                                        <td>
                                            <img src="{{ $category->getFirstMedia('image')->getUrl() }}"
                                                class="rounded" width="30" height="30"/>
                                        </td>
                                        <td>
                                            @canany(['modify-category'])
                                                <div class="btn-group btn-group-sm" aria-label="Basic example">
                                                    <a href="{{ route('admin.product-category.edit',$category->id) }}" class="btn btn-outline-warning"><i class="ft-edit-3"></i> Edit</a>
                                                    <button type="button" class="btn btn-outline-danger delete" data-route="{{route('admin.product-category.destroy',$category->id)}}"><i class="ft-trash-2"></i> Delete</button>
                                                </div>
                                            @endcanany
                                        </td>
                                    </tr>
                                @empty
                                    <tr><td colspan="3">No Data</td></tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-script')
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>

<script>
    $(document).ready(function(){
        if($('#sortable').length > 0){

            $("#sortable td").each(function () {
                $(this).css("width", $(this).width());
            });

            $('#sortable').sortable({
                scroll: false,
                handle: '.handle',
                update: function (event, ui) {
                    var order_id = [];

                    $('.overlay').show();
                    $("#sortable tr").each(function(index) {
                        order_id.push($(this).data('id'));
                    });
                    $.ajax({
                        type:'POST',
                        url:'/admin/set-order-category',
                        data: {order_id:order_id},
                        success:function(data){

                            if(data.success){
                                swal({
                                    title: 'Done',
                                    text: "Updated Successfully!",
                                    icon: 'success',
                                    timer: 1000,
                                });
                            }
                        },
                        error: function(){
                            swal({
                                title: 'Error',
                                text: "Error While Updating!",
                                icon: 'error',
                                timer: 1000,
                            });
                        }
                    });


                }
            });
            $( "#sortable" ).disableSelection();
        }

    })
</script>
@endsection