routes/web.php
<?php

Route::get('/',function(){
    return redirect()->route('login');
});

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });

    Route::group(['middleware' => 'auth','prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);

        Route::group(['middleware' => ['permission:view-product|modify-product']],function(){
            Route::resource('product','ProductController');
        });

        Route::group(['middleware' => ['permission:view-category|modify-category']],function(){
            Route::resource('product-category','ProductCategoryController');
        });

        Route::group(['middleware' => ['permission:view-setting|setting-modification']], function () {
            Route::resource('settings','SettingController');
        });
        Route::group(['middleware' => ['permission:view-language|language-modification']], function () {
            Route::resource('languages','LanguageController');
        });
        Route::group(['middleware' => ['permission:view-user|user-modification|add-new-user']], function () {
            Route::resource('/users','UserController');
        });
        Route::group(['middleware' => ['permission:view-role|role-modification|add-new-role']], function () {
            Route::resource('/roles','UserRoleController');
        });
        Route::resource('/users/profile','EditProfileController',['as' => 'users']);

        //ajax upload image
        Route::post('/save-temp-image', ['as' => 'dropzoneSaveTempImage', 'uses' => 'ImageController@dropzoneSaveTempImage']);
        Route::post('/save-multi-temp-image', ['as' => 'dropzoneSaveMultiTempImage', 'uses' => 'ImageController@dropzoneSaveMultiTempImage']);
        Route::post('/save-summernote-image',['as' => 'summernoteSaveImage', 'uses' => 'ImageController@summernoteSaveImage']);
        Route::get('/get-image-list-by-object',['as' => 'getImageList', 'uses' => 'ImageController@getImageList']);
        Route::post('/delete-image-by-object',['as' => 'deleteDropzoneImage', 'uses' => 'ImageController@deleteDropzoneImage']);
        Route::post('/set-order-category',['as' => 'setOrderCategory', 'uses' => 'ProductCategoryController@setOrder']);
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\Models\Media;

class User extends Authenticatable implements HasMedia
{
    use Notifiable, HasRoles, HasMediaTrait;

    protected $fillable = [ 
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct(){
        $this->middleware('permission:view-user',   ['only' => ['index']]);
        $this->middleware('permission:add-new-user',   ['only' => ['create']]);
        $this->middleware('permission:user-modification',   ['only' => ['update','destroy']]);
    }

    public function index()
    {
        $users = User::paginate(15);
        return view('admin.user.index',compact('users'));
    }

    public function create()
     {
         $roles = [0 => 'Choose a role'] + Role::all()->pluck('name','id')->toArray();
         return view('admin.user.add-update',compact('roles'));
     }
 
     public function store(Request $request)
     {
         $this->validate($request,[
             'name' => 'required|unique:users,name',
             'email' => 'required|unique:users,email',
             'password' => 'required|confirmed|min:6',
             'password_confirmation' => 'required|min:6'
         ]);
         
         $this->saveToDB($request->all());
         return redirect()->route('admin.users.index')->withSuccess('You have just added a user successfully!');
     }

     public function edit($id)
     {
         $roles = [0 => 'Choose a role'] + Role::all()->pluck('name','id')->toArray();
         $user = User::findOrFail($id);
         return view('admin.user.add-update',compact('roles','user'));
     }
 
     public function update(Request $request, $id)
     {
         $this->validate($request,[
             'name' => 'required|unique:users,name,'.$id,
             'email' => 'required|unique:users,email,'.$id
         ]);
         
         if($request->password){
             $this->validate($request,[
                 'password' => 'required|confirmed|min:6',
                 'password_confirmation' => 'required',
             ]);
         }
 
         $this->saveToDB($request->all(),$id);
         return redirect()->route('admin.users.index')->withSuccess('You have just updated a user successfully!');
     }

     public function destroy($id)
     {
        $result = false;
        $user = User::find($id);
        if($user){
            DB::beginTransaction();
            try{
                if($user->delete()){
                    $result = true;
                }
                DB::commit();
            }catch(Exception $exception){
                DB::rollback();
                $result = false;
            }
        }
        return response()->json(['success' => $result]);
     }

    public function deleteImage(){
        $result = false;
        $user_id = request()->get('user_id');
        DB::beginTransaction();
        try{
            $user = User::findOrFail($user_id);
            if($user){
                $user->clearMediaCollection('images');
                $result = true;
            }
            DB::commit();
        }catch(Exception $exception){
            DB::rollback();
            $result = false;
        }
        
        return response()->json(['success' => $result]);
    }

     public function saveToDB($data, $id=null){
         DB::beginTransaction();
         try{
             $user = isset($id) ? User::find($id) : new User;
             if(!$user) return redirect()->back()->withError('There is no record found!');
    
             if($data['password']){
                 $data['password'] = Hash::make($data['password']);
             }else{
                 unset($data['password']);
             }
             $user->fill($data);
             if($user->save()){
                $role = Role::find($data['role_id']);
                if($role) $user->syncRoles([$role->name]);
                saveModelSingleImage($user,$data['profileDropzoneImage'],'images');
             }

             DB::commit();
         }catch(Exception $ex){
             DB::rollback();
             return redirect()->back()->withError('There was an error during operation!');
         }
         return $user;
     }
}

resources/views/admin/user/role/add-update.blade.php
@extends('admin.layouts.master')

@section('page-css')
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/vendors.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/forms/icheck/icheck.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/forms/icheck/custom.css">
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">            
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ isset($role) ? 'Update' : 'Add' }} Administrator Roles</h4>
            </div>

            @if(isset($role))
            {{ Form::model($role,['route' => ['admin.roles.update',$role->id], 'method' => 'PUT']) }}
            @else
            {{ Form::open(['route' => 'admin.roles.store', 'method' => 'POST']) }}
            @endif
            @csrf
            <div class="card-content">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <fieldset class="form-group">
                                <label for="basicInput">Role Name</label>
                                {!! Form::text('name',null,['class' => 'form-control', 'placeholder' => 'Enter role name']) !!}
                                @component('admin.common.error_helper_text',['key' => "name"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="basicInput">Permissions</label>
                                @foreach(permissions() as $m => $module)
                                    <div class="row skin skin-square mb-2">
                                        <div class="col-12">
                                            <fieldset>
                                                {{Form::checkbox("permissions[$m][]",'0',isset($modules) && in_array($m,$modules)?true:false,["class" => "module"])}}
                                                <label class="strong"><strong>{{$module['module']}}</strong></label>
                                            </fieldset>
                                        </div>
                                        <div class="col-12 permission-list">
                                            @foreach($module['permissions'] as $p)
                                                <div class="d-inline-block mr-2">
                                                    <fieldset>
                                                        {{Form::checkbox("permissions[$m][]",$p['value'],isset($role) && in_array($p['value'],$role->permissions->pluck('name')->toArray())?true:false,["class" => "permission"])}}
                                                        <label>{{ $p['text'] }}</label>
                                                    </fieldset>
                                                </div>
                                            @endforeach
                                        </div>  
                                    </div>
                                @endforeach
                            </fieldset>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{route('admin.roles.index')}}" class="btn grey btn-outline-secondary">Discard</a>
                    <button type="submit" class="btn btn-outline-primary">Save changes</button>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

@section('page-script')
<script src="/app-assets/vendors/js/forms/icheck/icheck.min.js"></script>
<script src="/app-assets/js/scripts/forms/checkbox-radio.js"></script>
<script>
    $(document).ready(function(){
        $('.skin-square input').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
        // Set checkbox on Role Set
        if($('.module').length > 0){
            $('.module').parent().find('.iCheck-helper').click(function(){
                if($(this).parent().find('input').is(':checked')){
                    $(this).parents('.skin-square').find('.permission').each(function(){
                        $(this).parent().addClass('checked');
                        $(this).prop('checked', true);
                    })
                }else{
                    $(this).parents('.skin-square').find('.permission').each(function(){
                        $(this).parent().removeClass('checked');
                        $(this).prop('checked', false);
                    })
                }
            })
        }
        if($('.permission').length > 0){
            $('.permission').parent().find('.iCheck-helper').click(function(){
                var hasOnePermission = false;
                $(this).parents('.skin-square').find('.module').prop('checked', true);
                $(this).parents('.skin-square').find('.module').parent().addClass('checked');
                if($(this).parents('.skin-square').find('.module').is(':checked')){ 
                    $(this).parents('.skin-square').find('.module').prop('checked', true);
                    $(this).parents('.skin-square').find('.module').parent().addClass('checked');
                }
                $(this).parents('.permission-list').find('.permission').each(function(){
                    if($(this).is(':checked')){
                        hasOnePermission = true;
                    }
                })
                if(!hasOnePermission){
                    $(this).parents('.skin-square').find('.module').prop('checked', false);
                $(this).parents('.skin-square').find('.module').parent().removeClass('checked');
                }

            });
        }
        // End checkbox on Role Set
    })
</script>
@endsection

resources/views/admin/user/role/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">            
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Administrator Roles</h4>
                @can('add-new-role')
                <div class="heading-elements">
                    <a href="{{route('admin.roles.create')}}" class="btn btn-sm btn-icon btn-success">
                        <i class="ft-plus white"></i> Add New
                    </a>
                </div>
                @endcan
            </div>
            <div class="card-content">
                <div class="card-body">
                    @include('admin.includes.success-msg')
                    @include('admin.includes.error-msg')
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="thead-light">
                                <th>#</th>
                                <th>Role</th>
                                <th>Action</th>
                            </thead>
                            <tbody>
                                <tr>
                                    @if(isset($roles) && $roles->count() > 0) 
                                        @foreach($roles as $key => $row)
                                        <tr>
                                            <td>{{($roles->perPage() * ($roles->currentPage() - 1)) + $key + 1}}</td>
                                            <td>{{ $row->name }}</td>
                                            <td class="group-btn-action">
                                                @canany(['role-modification'])
                                                    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                                        <a href="{{ route('admin.roles.edit',$row->id) }}" class="btn btn-outline-warning"><i class="ft-edit-3"></i> Edit</a>
                                                        <button type="button" class="btn btn-outline-danger delete" data-route="{{route('admin.roles.destroy',$row->id)}}"><i class="ft-trash-2"></i> Delete</button>
                                                    </div>
                                                @endcanany
                                            </td>
                                        </tr>
                                        @endforeach
                                    @else 
                                        <tr><td colspan="3">No Data</td></tr>
                                    @endif
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @if(isset($roles) && $roles->count() > 0)
            <div class="card-footer">
                <div class="mb-2">
                    {!! $roles->appends(Input::except('page'))->render() !!}
                </div>
                <div>
                    Showing {{$roles->firstItem()}} to {{$roles->lastItem()}}
                    of  {{$roles->total()}} entries
                </div>
            </div>
            @endif
        </div>
    </div>
</div>
@endsection