routes/web.php
<?php

Route::get('/',function(){
    return redirect()->route('login');
});

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });

    Route::group(['middleware' => 'auth','prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);

        Route::group(['middleware' => ['permission:view-product|modify-product']],function(){
            Route::resource('product','ProductController');
        });

        Route::group(['middleware' => ['permission:view-category|modify-category']],function(){
            Route::resource('product-category','ProductCategoryController');
        });

        Route::group(['middleware' => ['permission:view-setting|setting-modification']], function () {
            Route::resource('settings','SettingController');
        });
        Route::group(['middleware' => ['permission:view-language|language-modification']], function () {
            Route::resource('languages','LanguageController');
        });
        Route::group(['middleware' => ['permission:view-user|user-modification|add-new-user']], function () {
            Route::resource('/users','UserController');
        });
        Route::group(['middleware' => ['permission:view-role|role-modification|add-new-role']], function () {
            Route::resource('/roles','UserRoleController');
        });
        Route::resource('/users/profile','EditProfileController',['as' => 'users']);

        //ajax upload image
        Route::post('/save-temp-image', ['as' => 'dropzoneSaveTempImage', 'uses' => 'ImageController@dropzoneSaveTempImage']);
        Route::post('/save-multi-temp-image', ['as' => 'dropzoneSaveMultiTempImage', 'uses' => 'ImageController@dropzoneSaveMultiTempImage']);
        Route::post('/save-summernote-image',['as' => 'summernoteSaveImage', 'uses' => 'ImageController@summernoteSaveImage']);
        Route::get('/get-image-list-by-object',['as' => 'getImageList', 'uses' => 'ImageController@getImageList']);
        Route::post('/delete-image-by-object',['as' => 'deleteDropzoneImage', 'uses' => 'ImageController@deleteDropzoneImage']);
        Route::post('/set-order-category',['as' => 'setOrderCategory', 'uses' => 'ProductCategoryController@setOrder']);
    });
});

resources/views/admin/layouts/head.blade.php
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="Stack admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
<meta name="keywords" content="admin template, stack admin template, dashboard template, flat admin template, responsive admin template, web app">
<meta name="author" content="PIXINVENT">
<title>Admin - Cambodia Alumni Association</title>
<link rel="apple-touch-icon" href="/client/images/logo.png">
<link rel="shortcut icon" type="image/x-icon" href="/client/images/logo.png">
<meta name="csrf-token" content="{{ csrf_token() }}" />
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

<!-- BEGIN: Vendor CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/vendors.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/extensions/unslider.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/weather-icons/climacons.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/fonts/meteocons/style.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/charts/morris.css">
<!-- END: Vendor CSS-->

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/bootstrap-extended.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/colors.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/components.css">
<!-- END: Theme CSS-->

<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/menu/menu-types/vertical-menu-modern.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/menu/menu-types/vertical-menu.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/colors/palette-gradient.css">
<link rel="stylesheet" type="text/css" href="/app-assets/fonts/simple-line-icons/style.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/colors/palette-gradient.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/pages/timeline.css">
<!-- END: Page CSS-->

<link rel="stylesheet" type="text/css" href="/app-assets/custom/css/custom.css">

@yield('page-css')
@yield('custom-css')

resources/views/admin/layouts/header.blade.php
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu fixed-top navbar-semi-light bg-gradient-x-grey-blue">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item"><a class="navbar-brand" href=""><img class="brand-logo rounded-circle" alt="stack admin logo" src="/icon_logo.jpg" width="25px;">
                        <h2 class="brand-text">{{ config('app.name') }}</h2>
                    </a></li>
                <li class="nav-item d-md-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="fa fa-ellipsis-v"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu"></i></a></li>
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon ft-maximize"></i></a></li>
                </ul>
                <ul class="nav navbar-nav float-right">
                    @php $auth = auth()->user(); $image = $auth->getFirstMedia('images'); @endphp
                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <span class="avatar avatar-online"><img class="rounded-circle" src="{{ $image ? $image->getUrl() : ''}}" alt="{{$auth->name}}"><i></i></span>
                            <span class="user-name">{{ $auth ? $auth->name : 'Big Biz' }}</span></a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="{{route('admin.users.profile.edit',$auth->id)}}"><i class="ft-user"></i> Edit Profile</a>
                            <a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();"><i class="ft-power"></i> Logout</a>
                            <form id="frm-logout" action="{{route('logout')}}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<head>
    @include('admin.layouts.head')
    @yield('page-style')
    @yield('dropzone-css')
</head>
<body class="vertical-layout vertical-menu 2-columns   fixed-navbar" data-open="click" data-menu="vertical-menu" data-col="2-columns">
    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                @yield('content')
            </div>
        </div>
    </div>
    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>
    <footer class="footer footer-static footer-dark navbar-border">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2"><span class="float-md-left d-block d-md-inline-block">Copyright &copy; {{date('Y')}} <a href="/" class="text-bold-800 grey darken-2" target="_blank">On-Sale Cambodia </a></span><span class="float-md-right d-none d-lg-block">Powered By <a class="text-bold-800 grey darken-2" href="https://www.mkoratec.com" target="_blank">MKORATEC </a></span></p>
    </footer>
    @include('admin.layouts.script')
    @yield('dropzone-script')
    @yield('page-script')
</body>
</html>

resources/views/admin/layouts/script.blade.php
<!-- BEGIN: Vendor JS-->
<script src="/app-assets/vendors/js/vendors.min.js"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="/app-assets/vendors/js/charts/raphael-min.js"></script>
<script src="/app-assets/vendors/js/charts/morris.min.js"></script>
<script src="/app-assets/vendors/js/extensions/unslider-min.js"></script>
<script src="/app-assets/vendors/js/timeline/horizontal-timeline.js"></script>
<script src="/app-assets/vendors/js/forms/icheck/icheck.min.js"></script>
<script src="/app-assets/vendors/js/extensions/sweetalert.min.js"></script>
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="/app-assets/js/core/app-menu.js"></script>
<script src="/app-assets/js/core/app.js"></script>
<!-- END: Theme JS-->

<!-- BEGIN: Page JS-->
<script src="/app-assets/js/scripts/pages/dashboard-ecommerce.js"></script>
<script src="/app-assets/js/scripts/extensions/sweet-alerts.js"></script>
<script type="text/javascript">
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>
<script>
    $(".nav-item a").each(function() {
    if ((window.location.href.indexOf($(this).attr('href'))) > -1) {
        $(this).parent().addClass('active');
    }
});
</script>
<!-- END: Page JS-->
<script src="/app-assets/custom/js/sidebar.js"></script>
<script src="/app-assets/custom/js/custom.js"></script>
@yield('custom-js')

resources/views/admin/layouts/sidebar.blade.php
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">

            @canany(['view-product'])
            <li class="nav-item"><a href="{{ route('admin.product.index') }}"><i class="ft-settings"></i><span class="menu-title" data-i18n="">Products</span></a>
            </li>
            @endcanany
            @canany(['view-product-category'])
            <li class="nav-item"><a href="{{ route('admin.product-category.index') }}"><i class="ft-settings"></i><span class="menu-title" data-i18n="">Product Category</span></a>
            </li>
            @endcanany
            @canany(['view-setting','setting-modification'])
            <li class="nav-item"><a href="{{ route('admin.settings.index') }}"><i class="ft-settings"></i><span class="menu-title" data-i18n="">Company Setting</span></a>
            </li>
            @endcanany

            {{-- @canany(['view-language','language-modification'])
            <li class=" nav-item"><a href="{{ route('admin.languages.index') }}"><i class="ft-globe"></i><span class="menu-title" data-i18n="">Languages</span></a>
            </li>
            @endcanany --}}

            @canany(['view-user','user-modification','add-new-user','view-role','role-modification','add-new-role'])
            <li class="nav-item has-sub"><a href="#"><i class="ft-unlock"></i><span class="menu-title" data-i18n="">Administrators</span></a>
                <ul class="menu-content" style="">
                    @canany(['view-user','user-modification','add-new-user'])
                    <li class=""><a class="menu-item" href="{{ route('admin.users.index') }}">Users</a>
                    </li>
                    @endcanany

                    @canany(['view-role','role-modification','add-new-role'])
                    <li class=""><a class="menu-item" href="{{ route('admin.roles.index') }}">Roles</a>
                    </li>
                    @endcanany
                </ul>
            </li>
            @endcanany
        </ul>
    </div>
</div>