routes/web.php
<?php

Route::get('/',function(){
    return redirect()->route('login');
});

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });

    Route::group(['middleware' => 'auth','prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);

        Route::group(['middleware' => ['permission:view-product|modify-product']],function(){
            Route::resource('product','ProductController');
        });

        Route::group(['middleware' => ['permission:view-category|modify-category']],function(){
            Route::resource('product-category','ProductCategoryController');
        });

        Route::group(['middleware' => ['permission:view-setting|setting-modification']], function () {
            Route::resource('settings','SettingController');
        });
        Route::group(['middleware' => ['permission:view-language|language-modification']], function () {
            Route::resource('languages','LanguageController');
        });
        Route::group(['middleware' => ['permission:view-user|user-modification|add-new-user']], function () {
            Route::resource('/users','UserController');
        });
        Route::group(['middleware' => ['permission:view-role|role-modification|add-new-role']], function () {
            Route::resource('/roles','UserRoleController');
        });
        Route::resource('/users/profile','EditProfileController',['as' => 'users']);

        //ajax upload image
        Route::post('/save-temp-image', ['as' => 'dropzoneSaveTempImage', 'uses' => 'ImageController@dropzoneSaveTempImage']);
        Route::post('/save-multi-temp-image', ['as' => 'dropzoneSaveMultiTempImage', 'uses' => 'ImageController@dropzoneSaveMultiTempImage']);
        Route::post('/save-summernote-image',['as' => 'summernoteSaveImage', 'uses' => 'ImageController@summernoteSaveImage']);
        Route::get('/get-image-list-by-object',['as' => 'getImageList', 'uses' => 'ImageController@getImageList']);
        Route::post('/delete-image-by-object',['as' => 'deleteDropzoneImage', 'uses' => 'ImageController@deleteDropzoneImage']);
        Route::post('/set-order-category',['as' => 'setOrderCategory', 'uses' => 'ProductCategoryController@setOrder']);
    });
});

resources/views/admin/common/error_helper_text.blade.php
@if($errors->has($key))
<p style="color:red !important"><small id="{{ isset($id) ? $id : ''}}">{{ $errors->first($key) }}</small></p>
@endif

resources/views/admin/common/multi_dropzone.blade.php
@section('dropzone-css')
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/file-uploaders/dropzone.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/ui/prism.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/file-uploaders/dropzone.css">
@endsection

<style>
    .dropzone .dz-preview .dz-image img{
        width:100%;
    }
    .dropzone .dz-preview .dz-image{
        width: @php echo $width.'px' @endphp !important;
        height: @php echo $height.'px' @endphp !important;
    }
</style>

@php 
    $collection_key = isset($collection_key) ? $collection_key : 'album'; 
    $imageId = $id.'Image';
    $actionId = $id.'Action';
    $deleteId = $id.'Delete';
@endphp

<div class="dropzone multi needsclick dz-clickable" action="{{ route('admin.dropzoneSaveMultiTempImage') }}" id="{{$id}}"
    data-width="{{$width}}" data-height="{{$height}}" data-input="{{$imageId}}" data-action="{{$actionId}}" data-delete="{{$deleteId}}"
    data-route-get-image="{{ route('admin.getImageList') }}" data-route-delete-image="{{ route('admin.deleteDropzoneImage') }}"
    data-model="{{isset($object) ? get_class($object) : ''}}" data-collection={{$collection_key}}>
    @csrf
</div>
@component('admin.common.error_helper_text',['key' => $imageId])@endcomponent

@if($object)
    <input type="hidden" name="{{$imageId}}" id="{{$imageId}}" value="{{old('image')}}" data-model-id="{{$object->id}}">
@else
    <input type="hidden" name="{{$imageId}}" id="{{$imageId}}" value="">
@endif
<input type="hidden" name="{{$actionId}}" id="{{$actionId}}" value="{{isset($object) ? 'update' : 'add'}}">
<input type="hidden" name="{{$deleteId}}" id="{{$deleteId}}" value="">


@section('dropzone-script')
<script src="/app-assets/vendors/js/extensions/dropzone.min.js"></script>
<script src="/app-assets/vendors/js/ui/prism.min.js"></script>
<script src="/app-assets/custom/js/dropzone.js"></script>
@endsection

resources/views/admin/common/single_dropzone.blade.php
@section('dropzone-css')
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/file-uploaders/dropzone.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/ui/prism.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/file-uploaders/dropzone.css">
@endsection

<style>
    #{{$id}} .dz-preview .dz-image img{
        width:100%;
    }
    #{{$id}} .dz-preview .dz-image{
        width: @php echo $width.'px' @endphp !important;
        height: @php echo $height.'px' @endphp !important;
    }
</style>

@php 
    $collection_key = isset($collection_key) ? $collection_key : 'images'; 
    $image = isset($object) ? $object->getMedia($collection_key)->first() : null; 
    $imageId = $id.'Image';
    $actionId = $id.'Action';
@endphp

<div class="dropzone needsclick dz-clickable" action="{{ route('admin.dropzoneSaveTempImage') }}" id="{{$id}}"
    data-width="{{$width}}" data-height="{{$height}}" data-input="{{$imageId}}" data-action="{{$actionId}}">
    @csrf
</div>
@component('admin.common.error_helper_text',['key' => $imageId])@endcomponent

@if($image)
    <input type="hidden" name="{{$imageId}}" id="{{$imageId}}" value="{{old('image')}}" data-model-id="{{$object->id}}" data-name="{{$image->file_name}}" data-size="{{$image->size}}" data-url="{{ asset($image->getUrl()) }}">
@else
    <input type="hidden" name="{{$imageId}}" id="{{$imageId}}" value="">
@endif
<input type="hidden" name="{{$actionId}}" id="{{$actionId}}" value="{{isset($object) ? 'update' : 'add'}}">


@section('dropzone-script')
<script src="/app-assets/vendors/js/extensions/dropzone.min.js"></script>
<script src="/app-assets/vendors/js/ui/prism.min.js"></script>
<script src="/app-assets/custom/js/dropzone.js"></script>
@endsection

resources/views/admin/common/success_alert.blade.php
@php $key = isset($key) ? $key : 'success' @endphp
@if(session()->has($key))
<div class="alert alert-success mb-2" role="alert">
    <strong>{{ session()->get($key)}}</strong> 
</div>
@endif